source 'https://rubygems.org'

gem 'rails',          '5.0.0.1'
gem 'sqlite3'
gem 'puma',           '~> 3.6'
gem 'figaro'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'byebug', platform: :mri
end
